---
- hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Install python for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python3-minimal)"
      register: output
      changed_when: output.stdout != ""
    - name: Gathering Facts
      setup:

- hosts: lain.rael.io
  become: true
  roles:
    - common
    - wifi
    - geerlingguy.docker

- hosts: do.play4trophies.com
  become: true
  roles:
    - common
    - p4t
    - geerlingguy.docker
  collections:
    - community.mysql
    - community.general
  vars:
    database_dumps_timestamp: "20220409"
