---
- name: Reload apache2 service
  service:
    name: apache2
    state: reloaded

- name: Restart apache2 service
  service:
    name: apache2
    state: restarted

- name: Restart php5.6-fpm service
  service:
    name: php5.6-fpm
    state: restarted
