---
- name: "{{ common__username }} user is present"
  group:
    name: "{{ common__username }}"

- name: "{{ common__username }} user is present"
  user:
    name: "{{ common__username }}"
    comment: "{{ common__username }} user"
    group: "{{ common__username }}"
    shell: "/bin/bash"
    generate_ssh_key: yes
    ssh_key_bits: "2048"
    ssh_key_file: ".ssh/id_rsa"

- name: "{{ common__username }} user is able to execute passwordless sudo"
  copy:
    dest: "/etc/sudoers.d/{{ common__username }}"
    content: "{{ common__username }} ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"

- name: "{{ common__username }} authorized_key contains the git public keys"
  authorized_key:
    user: "{{ common__username }}"
    state: present
    key: "https://github.com/{{ common__github_username }}.keys"
